USE DATABASE DE_2;

-- 05_model_dw.sql
CREATE OR REPLACE TABLE DW.FCT_WEATHER AS
SELECT
    LOCATION_NAME,
    DATE_TRUNC('hour', TIME) AS HOUR,
    AVG(TEMPERATURE) AS AVG_TEMPERATURE,
    SUM(PRECIPITATION) AS TOTAL_PRECIPITATION
FROM STG.WEATHER_HOURLY
GROUP BY 1,2;

-- Check DW table
SELECT * FROM DW.FCT_WEATHER LIMIT 10;
